### ISSUE TITLE
Boolean variables naming 

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#1]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/App.js#L8

Best practice to name boolean variables with prefix **is**

for example
isGameStarted

**Comment by valeriamrk** [comment]
fixed 
https://github.com/valeriamrk/memory-game/commit/939967cdd9efea5adf572619272c452b031b3265
