### ISSUE TITLE
Empty div

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#12]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/components/presentational/pages/gamePage/GamePage.jsx#L165

Empty div tag will be render in DOM
If you dont need this and you want return nothing, you can use React.Fragment syntax (short syntax <></>)
Docs: https://ru.react.js.org/docs/fragments.html#short-syntax
or return null

Current result:
`<div></div>`

Expected result:
`<></>` or null

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/9d2ceb6bd104402f1853fb2bf412bcc6a73eb900
