### ISSUE TITLE
Classname syntax

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#13]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/components/presentational/pages/gamePage/GamePage.jsx#L171

**Current result:**
`<div className={"card-grid"}>`

**Expected result:**
`<div className="card-grid">`

or maybe use camelCase
`<div className="cardGrid">`

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/39bf5464ca23e697dafa5d9d9256da0bbc88910f
