### ISSUE TITLE
Button default tag

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#14]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/components/presentational/pages/gamePage/GamePage.jsx#L155-L156

You have own button component, but you dont use them
**/src/components/presentational/atoms/myButton.jsx**

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/c4815d8fa6c7fd0f99968ac93ccd2c774b4b808f
