### ISSUE TITLE
Index for export/import all pages

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#16]
https://github.com/valeriamrk/memory-game/blob/4404c2db3e03794af02e8e10e878e3ae7a40ee9b/src/App.jsx#L3-L4

**Current result:**
```
import GamePage from "./pages/gamePage/GamePage"
import WelcomePage from "./pages/welcomePage/WelcomePage"
```

**Expected result:**
`import { GamePage, WelcomePage } from "./pages"`

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/451101e9ce37d2727701edeb02e14e263c13c332
