### ISSUE TITLE
Not obvious import path

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#18]
https://github.com/valeriamrk/memory-game/blob/4404c2db3e03794af02e8e10e878e3ae7a40ee9b/src/components/presentational/organisms/lose/Lose.jsx#L2

**Current result:**
`import { MyButton } from "../..";
`
**Expected result:**
`import { MyButton } from "../../../presentational";`

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/d22987261a9dfad0d4160ad18a9431bc4d37b797
