### ISSUE TITLE
Css classname syntax

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#19]
https://github.com/valeriamrk/memory-game/blob/4404c2db3e03794af02e8e10e878e3ae7a40ee9b/src/components/presentational/organisms/modal/MyModal.jsx#L23

camelCase

**Current result:**
`className="modal__content" `

**Expected result:**
`className="modalContent" `

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/c9f5cf4782eda0696f5ec40379398f36b7733047
