### ISSUE TITLE
Molecule in organism - folder structure

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#21]
<img width="252" alt="Screenshot 2022-06-16 at 18 31 47" src="https://user-images.githubusercontent.com/42766161/174106605-2e652718-d60c-42f2-877c-2c59c6ca328d.png">

Single Card is a part of All Cards

**Current result:**
Single Card - organism
All Cards - organism

**Expected result:**
Single Card - molecule
All Cards - organism

**Maybe Win and Lose components also molecules ?**

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/ea48f9ce2af80bc9f2dedc0dcb6111becf22f201
https://github.com/valeriamrk/memory-game/commit/5ea5f019c6bfa02c1c20c3e298853dd0f2806cc3
