### ISSUE TITLE
Components folder structure

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#22]
<img width="239" alt="Screenshot 2022-06-16 at 18 37 24" src="https://user-images.githubusercontent.com/42766161/174108005-daddb8e0-1f90-4a12-bb24-6fd09c499f2d.png">

Presentation folder in prod is not good, you dont have another components types
You can export all components from components folder

**Current result:**
src\components\presentation

**Expected result:**
src\components

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/ea48f9ce2af80bc9f2dedc0dcb6111becf22f201
