### ISSUE TITLE
Libraries not used in the project

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#23]
https://github.com/valeriamrk/memory-game/blob/4404c2db3e03794af02e8e10e878e3ae7a40ee9b/package.json#L5-L16

"@reduxjs/toolkit": "^1.8.1",
"animate.css": "^4.1.1",

uninstall libraries in your project and delete strings in package.json file

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/de469d52c970a13b63f8a873844747c5c8421591
