### ISSUE TITLE
Edit readme

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#24]
<img width="915" alt="Screenshot 2022-06-16 at 18 50 37" src="https://user-images.githubusercontent.com/42766161/174113249-08f70eb4-1fc3-4a03-803f-e30ffa65c81b.png">

This is automatically generated readme file.
Change readme file for you project.
Insert information about your game: how to install, how to start/stop, game rules and instructions

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/e10ead14e33d233ed7d95802fd6b3a5972a846ac
