### ISSUE TITLE
Keys ids

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#25]
https://github.com/valeriamrk/memory-game/blob/4404c2db3e03794af02e8e10e878e3ae7a40ee9b/src/pages/gamePage/GamePage.jsx#L173

Main array of cards does not contain card.id variables

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/ceb688aec3f51a47f3d9032ae83168628513b595
