### ISSUE TITLE
Red warnings in console

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#26]
<img width="518" alt="Screenshot 2022-06-16 at 19 16 08" src="https://user-images.githubusercontent.com/42766161/174117779-4c68bb37-83bd-476e-a7cd-009eb2c00e4f.png">

Проблема не неправильном пробрасывании props в компонент когда делается spread остальных пропсов ...props

**Current result:**
<img width="722" alt="Screenshot 2022-06-16 at 19 17 55" src="https://user-images.githubusercontent.com/42766161/174118127-a9800246-2737-4156-8e56-7534801775c1.png">

**Expected result:**
<img width="732" alt="Screenshot 2022-06-16 at 19 20 19" src="https://user-images.githubusercontent.com/42766161/174118475-0674661f-d3e3-44e8-b57b-6942d40bab36.png">

**Также
Починить оставшиеся 2 красных предупреждения**
<img width="527" alt="Screenshot 2022-06-16 at 19 20 04" src="https://user-images.githubusercontent.com/42766161/174118561-af3360b5-da6a-4edc-b67a-350ff6163fcd.png">

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/d43d69029e944c9017f20ed8eea9d5b28c90c753
