### ISSUE TITLE
Pages folder path

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#3]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/App.js#L3

Change pages folder path

Current result:
_src/componets/pages_

Expected result:
_src/components_
_src/pages_

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/939967cdd9efea5adf572619272c452b031b3265
