### ISSUE TITLE
Not expected import SingleCard

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#7]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/components/presentational/pages/gamePage/GamePage.jsx#L2-L3

Current result:
```
import { Countdown, MyModal } from "../../../presentational";
import { SingleCard } from "../../organisms/singleCard/SingleCard";
```

Expected result:
`import { Countdown, MyModal, SingleCard } from "../../../presentational";`

**Comment by valeriamrk** [comment]
fixed
https://github.com/valeriamrk/memory-game/commit/939967cdd9efea5adf572619272c452b031b3265
