### ISSUE TITLE
Improve variable naming

### ISSUE THREAD

**Issue by linostin** [valeriamrk/memory-game#8]
https://github.com/valeriamrk/memory-game/blob/501a62e95a973d2c6d3889a6e0009a09a19105b8/src/components/presentational/pages/gamePage/GamePage.jsx#L28-L29

**Current result:**
handleChoice
choiceOne
choiceTwo

**Expected result:**
handleCardChoice
isFirstCardSelected
isSecondCardSelected

**Comment by valeriamrk** [comment]
fixed 
https://github.com/valeriamrk/memory-game/commit/b0697758724d449e740ecb6e9b64dd4df64d8d3b
